import "../config/firebase"; // Ensures firebase-admin app is initialized
import admin from "firebase-admin";
import AppError from "../error/AppError";
import httpStatus from "http-status";
import { verifyFirebaseAppleToken } from "./firebase.token";

/**
 * Verifies a Firebase ID Token generated by Apple sign-in.
 * 
 * @param idToken - The Firebase ID Token sent from the client.
 * @returns The decoded Firebase ID Token payload.
 */
export const verifyAppleToken = verifyFirebaseAppleToken;

