import "../config/firebase"; // Ensures firebase-admin app is initialized
import admin from "firebase-admin";
import AppError from "../error/AppError";
import httpStatus from "http-status";

/**
 * Verifies a Firebase ID Token generated by Apple sign-in.
 * 
 * @param idToken - The Firebase ID Token sent from the client.
 * @returns The decoded Firebase ID Token payload.
 */
export const verifyAppleToken = async (idToken: string): Promise<any> => {
  try {
    const decodedToken = await admin.auth().verifyIdToken(idToken);

    // Verify that the provider is apple.com
    const signInProvider = decodedToken.firebase?.sign_in_provider;
    if (signInProvider !== "apple.com") {
      throw new AppError(
        httpStatus.UNAUTHORIZED,
        "The provided token is not from Apple Sign-in via Firebase"
      );
    }

    return decodedToken;
  } catch (error: any) {
    console.error("[APPLE FIREBASE AUTH] Error verifying token:", error);
    throw new AppError(
      httpStatus.UNAUTHORIZED,
      `Apple verification failed: ${error.message}`
    );
  }
};
