import "../config/firebase"; // Ensures firebase-admin app is initialized
import admin from "firebase-admin";
import AppError from "../error/AppError";
import httpStatus from "http-status";

/**
 * Verifies a Firebase ID Token generated by Google sign-in.
 * 
 * @param idToken - The Firebase ID Token sent from the client.
 * @returns The decoded Firebase ID Token payload.
 */
export const verifyFirebaseGoogleToken = async (idToken: string): Promise<admin.auth.DecodedIdToken> => {
  try {
    const decodedToken = await admin.auth().verifyIdToken(idToken);

    const signInProvider = decodedToken.firebase?.sign_in_provider;
    if (signInProvider !== "google.com") {
      throw new AppError(
        httpStatus.UNAUTHORIZED,
        "The provided token is not from Google Sign-in via Firebase"
      );
    }

    return decodedToken;
  } catch (error: any) {
    if (error instanceof AppError) {
      throw error;
    }
    console.error("[GOOGLE FIREBASE AUTH] Error verifying token:", error);
    throw new AppError(
      httpStatus.UNAUTHORIZED,
      `Google verification failed: ${error.message || error}`
    );
  }
};

/**
 * Verifies a Firebase ID Token generated by Apple sign-in.
 * 
 * @param idToken - The Firebase ID Token sent from the client.
 * @returns The decoded Firebase ID Token payload.
 */
export const verifyFirebaseAppleToken = async (idToken: string): Promise<admin.auth.DecodedIdToken> => {
  try {
    const decodedToken = await admin.auth().verifyIdToken(idToken);

    const signInProvider = decodedToken.firebase?.sign_in_provider;
    if (signInProvider !== "apple.com") {
      throw new AppError(
        httpStatus.UNAUTHORIZED,
        "The provided token is not from Apple Sign-in via Firebase"
      );
    }

    return decodedToken;
  } catch (error: any) {
    if (error instanceof AppError) {
      throw error;
    }
    console.error("[APPLE FIREBASE AUTH] Error verifying token:", error);
    throw new AppError(
      httpStatus.UNAUTHORIZED,
      `Apple verification failed: ${error.message || error}`
    );
  }
};
